name: Prueba básica ROCKSI

on:
  push:
    branches: [ "Desarrollo" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compilar proyecto
        run: mvn clean install -DskipTests

      - name: Ejecutar pruebas
        run: mvn test